name: publish

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    name: Test, build and publish NPM package

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.30.3
          run_install: false

      - name: 🐧 Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24.14.0
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: 🔍 Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: 👮 Lint sources
        run: pnpm run lint

      - name: 🧪 Test
        run: pnpm run test

      - name: 🔧 Build
        run: pnpm run build

      - name: 👮 Lint package.json
        run: pnpm run publint

      - name: 🔬 Check size
        run: pnpm run size

      - name: 📦 Publish
        run: pnpm publish --access public --provenance --no-git-checks
        working-directory: build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
