name: try versions
run-name: Try different effector versions

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  try:
    strategy:
      matrix:
        effector:
          - npm:effector@22.0.0
          - npm:effector@22.8.6

    name: ${{ matrix.effector-version }}

    uses: ./.github/workflows/try.yml
    with:
      effector: ${{ matrix.effector }}
    secrets: inherit
