name: try versions
run-name: Try different effector versions

on:
  workflow_dispatch:
  registry_package:
    types:
      - published

jobs:
  try:
    strategy:
      matrix:
        effector:
          - npm:effector@22.4.0
          - npm:effector@22.8.8
          - npm:effector@23.0.0
          - npm:effector@23.2.2

    name: ${{ matrix.effector-version }}

    uses: ./.github/workflows/try.yml
    with:
      effector: ${{ matrix.effector }}
      effector-storage: ${{ github.event_name == 'registry_package' && format('npm:@{0}/effector-storage@{1}', github.repository_owner, github.event.registry_package.package_version.npm_metadata.version) || '' }}
    secrets: inherit
