name: try versions
run-name: Try different effector versions

on:
  workflow_dispatch:
  registry_package:
    types:
      - published

jobs:
  try:
    strategy:
      matrix:
        effector:
          - npm:effector@22.0.0
          - npm:effector@22.8.6

    name: ${{ matrix.effector-version }}

    uses: ./.github/workflows/try.yml
    with:
      effector: ${{ matrix.effector }}
      effector-storage: ${{ github.event_name == 'registry_package' && 'npm:@' + github.repository_owner + '/effector-storage@' + github.event.registry_package.package_version.npm_metadata.version || '' }}
    secrets: inherit
